version: 2.1

docker_infra: &docker_infra
  docker:
    - image: amazon/aws-cli

commands:
  run_create_infra:
    steps:
      - checkout
      - run:
          name: "Creating AWS Infrastructure..."
          command: "./cloudformation/create-infra.sh"

jobs:
  create_infra:
    <<: *docker_infra
    steps:
      - checkout
      - run_create_infra

workflows:
  continuous_deployment:
    jobs:
      - create_infra:
          type: approval
