version: 2.1

docker_default: &docker_default
  docker:
    - image: amazon/aws-cli

commands:
  print_hello:
    steps:
      - checkout
      - run:
          name: "printing hello world"
          command: "echo $AWS_ACCESS_KEY_ID"

jobs:
  create_infra:
    <<: *docker_default
    steps:
      - checkout
      - print_hello

workflows:
  say-hello-workflow:
    jobs:
      - create_infra
