version: 2.1

docker_default: &docker_default
  docker:
    - image: amazon/aws-cli

commands:
  run_create_infra:
    steps:
      - checkout
      - run:
          name: "Creating AWS Infrastructure..."
          command: "./create-infra.sh"

jobs:
  create_infra:
    <<: *docker_default
    steps:
      - checkout
      - run_create_infra

workflows:
  continuous_deployment:
    jobs:
      - create_infra
