---
- name: update apt packages
  become: true
  apt:
    update_cache: true
- name: upgrade apt packages
  become: true
  apt:
    upgrade: true
- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true
- name: install python and pip
  become: true
  apt:
    name: ["python3", "python3-pip"]
    state: latest
    update_cache: true
- name: create app dir
  become: true
  file:
    path: ~/bookmarks-api
    state: directory
# - name: copy project to directory
#   template:
#     src: "files/"
#     dest: "~/bookmarks-api"
- name: copy project to directory
  become: true
  copy:
    src: ../files/
    dest: /home/ubuntu/bookmarks-api
    owner: ubuntu
    group: ubuntu
- name: install project dependencies
  shell: |
    cd /home/ubuntu/bookmarks-api
    pip3 install -r requirements.txt

- name: start flask server
  become: true
  shell: |
    ls -al
    export FLASK_ENV=development
    export FLASK_APP=/home/ubuntu/bookmarks-api
    echo "starting flask server..."
    flask run
